export const ACTIVITY_LIST_REQUEST = 'ACTIVITY_LIST_REQUEST';
export const ACTIVITY_LIST_SUCCESS = 'ACTIVITY_LIST_SUCCESS';
export const ACTIVITY_LIST_FAIL = 'ACTIVITY_LIST_FAIL';

export const ACTIVITY_DELETE_REQUEST = 'ACTIVITY_DELETE_REQUEST';
export const ACTIVITY_DELETE_SUCCESS = 'ACTIVITY_DELETE_SUCCESS';
export const ACTIVITY_DELETE_FAIL = 'ACTIVITY_DELETE_FAIL';

export const ACTIVITY_CREATE_REQUEST = 'ACTIVITY_CREATE_REQUEST';
export const ACTIVITY_CREATE_SUCCESS = 'ACTIVITY_CREATE_SUCCESS';
export const ACTIVITY_CREATE_FAIL = 'ACTIVITY_CREATE_FAIL';
export const ACTIVITY_CREATE_RESET = 'ACTIVITY_CREATE_RESET;';

export const ACTIVITY_UPDATE_REQUEST = 'ACTIVITY_UPDATE_REQUEST';
export const ACTIVITY_UPDATE_SUCCESS = 'ACTIVITY_UPDATE_SUCCESS';
export const ACTIVITY_UPDATE_RESET = 'ACTIVITY_UPDATE_RESET';
