export const PARTICIPATION_CREATE_REQUEST = 'PARTICIPATION_CREATE_REQUEST';
export const PARTICIPATION_CREATE_SUCCESS = 'PARTICIPATION_CREATE_SUCCESS';
export const PARTICIPATION_CREATE_FAIL = 'PARTICIPATION_CREATE_FAIL';
export const PARTICIPATION_CREATE_RESET = 'PARTICIPATION_CREATE_RESET;';
