export const STUDENT_LIST_REQUEST = 'STUDENT_LIST_REQUEST';
export const STUDENT_LIST_SUCCESS = 'STUDENT_LIST_SUCCESS';
export const STUDENT_LIST_FAIL = 'STUDENT_LIST_FAIL';

export const STUDENT_BY_ACTIVITY_REQUEST = 'STUDENT_BY_ACTIVITY_REQUEST';
export const STUDENT_BY_ACTIVITY_SUCCESS = 'STUDENT_BY_ACTIVITY_SUCCESS';
export const STUDENT_BY_ACTIVITY_FAIL = 'STUDENT_BY_ACTIVITY_FAIL';
